### ISSUE TITLE
PINDA v2 BTT002 v1.0

### ISSUE THREAD

**Issue by lance23dooley** [thisiskeithb/PrusaAIO#27]
### Did you test the latest `prusa-aio-bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

BTT002 v1.0 Prusa Bear Pinda 4 pins will not detect and ends up crashing the nozzle into the bed ive tried everything including other pindas but the board wont detect them the pinda lights up but wont trigger the firmware.

### Version of PrusaAIO Firmware

AIO v2.1x

### Electronics

BTT002 V1.0

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

PrusaSlicer

### Host Software

Pronterface

### Don't forget to include

- [X] A ZIP file containing your `Prusa_AIO_Configuration.h`.

### Additional information & file uploads

[Prusa_AIO_Configuration.zip](https://github.com/thisiskeithb/PrusaAIO/files/10494511/Prusa_AIO_Configuration.zip)

**Comment by thisiskeithb** [comment]
Did you cut the diag pin on your Z driver? The PINDA won’t work with it attached.

Both the PINDA V2 and SuperPINDA work fine on the BTT002 boards here.

**Comment by lance23dooley** [comment]
> Did you cut the diag pin on your Z driver? The PINDA won’t work with it attached.
> 
> Both the PINDA V2 and SuperPINDA work fine on the BTT002 boards here.

do I need to cut diag on both tmc2209 z drivers

**Comment by thisiskeithb** [comment]
> do I need to cut diag on both tmc2209 z drivers

The BTT002 only has a single Z driver. Are you sure you have a BTT002 motherboard?

The two drivers that need diag pins cut when used on the BTT002 are Z and E.

**Comment by lance23dooley** [comment]
I think I was confusing another driver that was the E I've Been working on this since 6 am my brain is moosh lol

**Comment by lance23dooley** [comment]
I will have to cut those pins or desolder them once I rewire my case

**Comment by thisiskeithb** [comment]
I've added some additional warnings during compile time about diag pins/jumpers and updated the [Motherboards & Wiring Guide in the wiki](https://github.com/thisiskeithb/PrusaAIO/wiki/Supported-Motherboards-&-Wiring-Guide) with similar comments.
