### ISSUE TITLE
[BUG] PRUSA_AIO_THERMISTOR_GENERIC_100K

### ISSUE THREAD

**Issue by mojamuto** [thisiskeithb/PrusaAIO#31]
### Did you test the latest `prusa-aio-bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

When I select PRUSA_AIO_THERMISTOR_GENERIC_100K it doesn't compile and gives the following error:

```
Marlin/src/module/temperature.cpp:329:14: error: static assertion failed: HEATER_0_MAXTEMP (310) is too high for thermistor_1.h with HOTEND_OVERSHOOT=15.
```
selecting PRUSA_AIO_THERMISTOR_STOCK_SEMITEC_104NT compiles without problems

I just modified the file Prusa_AIO_Configuration.h
[Prusa_AIO_Configuration.h.zip](https://github.com/thisiskeithb/PrusaAIO/files/11567762/Prusa_AIO_Configuration.h.zip)

### Bug Timeline

New bug

### Expected behavior

compile the firmware

### Actual behavior

does not compile and gives the following error:

Marlin/src/module/temperature.cpp:329:14: error: static assertion failed: HEATER_0_MAXTEMP (310) is too high for thermistor_1.h with HOTEND_OVERSHOOT=15.

### Steps to Reproduce

1. clone repository
2. Open vscode
3. Modify Prusa_AIO_Configuration.h
4. compile

### Version of PrusaAIO Firmware

PRUSA_AIO_VERSION 20230520

### Electronics

skr 1.4

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

PrusaSlicer

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Prusa_AIO_Configuration.h`.

**Comment by thisiskeithb** [comment]
Thanks for the report!

I've patched this & rebased code on the latest upstream `bugfix-2.1.x`, so it will now successfully compile when `PRUSA_AIO_THERMISTOR_GENERIC_100K` is enabled.

**Comment by mojamuto** [comment]
tested and working thank you very much
