### ISSUE TITLE
When MMU is enabled and tried to compile the firmware the error is displayed

### ISSUE THREAD

**Issue by rajavel1990** [thisiskeithb/PrusaAIO#33]
### Did you test the latest `prusa-aio-bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

I tried to enable the MMU settings on the Configuration and Configuration_adv.h files.

When MMU is enabled and tried to compile the firmware the error is displayed. Below are the changes that were done on the files

**Configuration.h**

#define EXTRUDERS 5
#define PRUSA_MMU2

**Configuration_adv.h**

#define MMU2_SERIAL Serial
#define MMU2_MENUS
#define MMU2_DEBUG

<img width="1192" alt="Screenshot 2023-06-12 at 9 32 09 AM" src="https://github.com/thisiskeithb/PrusaAIO/assets/43663845/54d0a4d7-fb81-4ec5-8be8-e36e1a081617">

### Steps to Reproduce

**Configuration.h**

#define SERIAL_PORT -1
#define EXTRUDERS 5
#define PRUSA_MMU2

**Configuration_adv.h**

#define MMU2_SERIAL Serial
#define MMU2_MENUS
#define MMU2_DEBUG

### Version of PrusaAIO Firmware

prusa-aio-bugfix-2.1.x

### Electronics

SKR V 1.4 with TMC2209 and BTT MMU DIP with TMC2209

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Prusa_AIO_Configuration.h`.

### Additional information & file uploads

[Archive.zip](https://github.com/thisiskeithb/PrusaAIO/files/11717414/Archive.zip)

**Comment by thisiskeithb** [comment]
This fork does not support the MMU and you should not be editing files outside of `Prusa_AIO_Configuration.h`.
