### ISSUE TITLE
[BUG] Building Environment for SKR_MINI_E3_V2_0

### ISSUE THREAD

**Issue by Ranko91** [thisiskeithb/PrusaAIO#38]
### Did you test the latest `prusa-aio-bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

After making all of the changes in Config.h for SKR Mini E3 V2,0 and tryed to build it for STM32F103RE_btt or STM32F103RC_btt it shows Error: Error: Build environment 'STM32F103RE_btt' is incompatible with BOARD_BTT_SKR_V3_0_EZ. Use one of these environments: STM32H743VI_btt, STM32H723VG_btt. I changed everything already in Code: 
// Choose the name from boards.h that matches your setup
#ifndef MOTHERBOARD
 #define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V2_0
#endif

### Bug Timeline

New Bug

### Expected behavior

It should have written the Firmware for BTT SKR Mini E3 V2.0
// Choose the name from boards.h that matches your setup
#ifndef MOTHERBOARD
 #define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V2_0
#endif

### Actual behavior

It shows build environment for another board
Error: Build environment 'STM32F103RE_btt' is incompatible with BOARD_BTT_SKR_V3_0_EZ. Use one of these environments: STM32H743VI_btt, STM32H723VG_btt

### Version of Prusa AIO Firmware

Prusa AIO Bugfix V 2.1.x

### Electronics

BTT SKR Mini E3 V2.0

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Prusa_AIO_Configuration.h`.

### Additional information & file uploads

[PrusaAIO-prusa-aio-bugfix-2.1.x.zip](https://github.com/thisiskeithb/PrusaAIO/files/13785853/PrusaAIO-prusa-aio-bugfix-2.1.x.zip)

**Comment by Ranko91** [comment]
I saw my mistake in changing the board.

**Comment by thisiskeithb** [comment]
You should not be changing anything in `Configuration.h`. The only config changes that should be made are in `Prusa_AIO_Configuration.h`.

[From the readme](https://github.com/thisiskeithb/PrusaAIO#configuring-prusa-all-in-one-firmware):

<hr>

## Configuring Prusa All-in-One Firmware

To configure this firmware, enable options in [`Prusa_AIO_Configuration.h`](Marlin/Prusa_AIO_Configuration.h). No other config file editing is required!

<hr>

**Comment by Ranko91** [comment]
Thank you fir Firmware, it was my mistake, i didn't read the whole post, i
managed it now. So again, thank you a lot !
